CREATE TABLE DAILYREPORT(

  id INT(2) NOT NULL AUTO_INCREMENT,
  type_id INT(2) NOT NULL,
  created DATETIME NOT NULL,
  startTime TIME NOT NULL,
  endTime TIME NOT NULL,
  detail VARCHAR(20) NOT NULL,
  stuff_id INT NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE DAILYREPORT_TYPE(

  id INT NOT NULL,
  progress VARCHAR NOT NULL,
  PRIMARY KEY(id)
);



CREATE TABLE STUFF(
 
  id INT(2) NOT NULL AUTO_INCREMENT,
  type_id INT(2)  NOT NULL,
  name VARCHAR(20) NOT NULL,
  detail VARCHAR(20),
  PRIMARY KEY(id)
);


CREATE TABLE STUFF_TYPE(

 id INT(2) NOT NULL,
 department VARCHAR(20) NOT NULL,
 PRIMARY KEY(id)

);

CREATE TABLE SUPPLIER(

 id INT(2) NOT NULL AUTO_INCREMENT,
 type_id INT NOT NULL,
 name VARCHAR NOT NULL,
 PRIMARY KEY(id)
 
);

CREATE TABLE SUPPLIER_TYPE(
  id INT NOT NULL,
  type VARCHAR NOT NULL,
  PRIMARY KEY(id)
);

CREATE TABLE WORK(
  id INT(2) NOT NULL AUTO_INCREMENT,
  type_id INT NOT NULL,
  comment VARCHAR(20) NOT NULL,
  PRIMARY KEY(id)
);

CREATE TABLE WORK_TYPE(
  id INT NOT NULL,
  type VARCHAR NOT NULL,
  PRIMARY KEY(id)
);

